#!/usr/bin/env bash

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    # Install Nginx if not installed
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Configure Nginx for redirection
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Other server configurations...

}
EOL'

# Restart Nginx to apply changes
sudo service nginx restart

