#!/usr/bin/env bash

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    # Install Nginx if not installed
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Create a custom 404 error page
sudo bash -c 'echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html'

# Configure Nginx for custom 404 page
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }

    # Other server configurations...

}
EOL'

# Restart Nginx to apply changes
sudo service nginx restart

